Repository kavkaco/Kavka-Core, pull requests merged in 2023-09, with the labels that each got.

#8 feat: adding linter, issue and PR template and actions
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/linting.yml
  .github/workflows/semantic-pr.yml
  .github/workflows/testing.yml
  .golangci.yml
  CONTRIBUTING.md
  Makefile
  app/controller/user_controller.go
  app/dto/dto.go
  app/dto/user_dto.go
  app/presenters/chat_presenters.go
  app/presenters/user_presenter.go
  app/socket/chats_handler.go
  app/socket/messages_handler.go
  app/socket/socket_handler.go
  cmd/server/server.go
  config/config.go
  database/mongo.go
  database/mongo_test.go
  database/redis.go
  database/redis_test.go
  docs/logo.png
  go.mod
  go.sum
  internal/domain/chat/chat_entity.go
  internal/domain/message/message_entity.go
  internal/domain/user/user_entity.go
  internal/domain/user/user_profile_entity.go
  internal/repository/chat/chat_repository.go
  internal/repository/chat/chat_repository_test.go
  internal/repository/message/message_repository.go
  internal/repository/message/message_repository_test.go
  internal/repository/user/user_repository.go
  internal/repository/user/user_repository_test.go
  internal/service/chat_service.go
  internal/service/message_service.go
  internal/service/user_service.go
  pkg/jwt_manager/jwt_manager.go
  pkg/jwt_manager/jwt_manager_test.go
  pkg/session/session.go
  pkg/session/session_test.go
  pkg/uploader/uploader.go
  pkg/uploader/uploader_test.go
  utils/bearer/bearer.go
  utils/random/random.go
  utils/random/random_test.go
  utils/sms_otp/sms_otp.go
  utils/sms_otp/sms_otp_test.go
Labels: linter, CI/CD, test

#13 Refactor config package
  config/config.go
  config/configs.yml
  pkg/jwt_manager/jwt_manager.go
  pkg/jwt_manager/jwt_manager_test.go
  pkg/session/session.go
Labels: bug

#18 fix: broken pipline issue (gofumpt)
  app/controller/user_controller.go
  app/dto/dto.go
  app/middleware/error_handler.go
  app/presenters/chat_presenters.go
  app/presenters/user_presenter.go
  app/router/user_routes.go
  app/socket/chats_handler.go
  app/socket/socket_handler.go
  cmd/server/server.go
  database/mongo.go
  database/redis.go
  go.mod
  internal/domain/chat/chat_entity.go
  internal/domain/user/user_entity.go
  internal/repository/chat/chat_repository.go
  internal/repository/message/message_repository.go
  internal/repository/user/user_repository.go
  internal/service/chat_service.go
  internal/service/message_service.go
  internal/service/user_service.go
  pkg/jwt_manager/jwt_manager.go
  pkg/jwt_manager/jwt_manager_test.go
  pkg/session/session.go
  pkg/session/session_structs.go
  pkg/uploader/uploader.go
  utils/bearer/bearer.go
  utils/sms_otp/sms_otp.go
  utils/sms_otp/sms_otp_test.go
Labels: bug, linter, CI/CD

#24 fix: Random security issue
  utils/random/random.go
Labels: security, refactor

#27 refactor: mock repositories
  app/controller/user_controller.go
  app/router/user_routes.go
  app/socket/socket_handler.go
  cmd/server/server.go
  go.mod
  go.sum
  internal/domain/chat/chat_entity.go
  internal/domain/message/message_entity.go
  internal/domain/user/user_entity.go
  internal/repository/chat/chat_repository.go
  internal/repository/chat/chat_repository_mock.go
  internal/repository/chat/chat_repository_test.go
  internal/repository/message/message_repository.go
  internal/repository/message/message_repository_mock.go
  internal/repository/message/message_repository_test.go
  internal/repository/user/user_repository.go
  internal/repository/user/user_repository_mock.go
  internal/repository/user/user_repository_test.go
  internal/service/chat_service.go
  internal/service/message_service.go
  internal/service/user_service.go
Labels: test, refactor
